# v2.0.0
name: Build OneShell App

inputs:
  githubToken:
    description: "GitHub Token"
    required: true

runs:
  using: composite

  steps:

    - name: Install dependencies for OneShell App
      shell: bash
      working-directory: src/VirtoCommerce.OneShell.Web/one-shell-app
      run: yarn

    - name: Build OneShell App
      shell: bash
      working-directory: src/VirtoCommerce.OneShell.Web/one-shell-app
      run: yarn build

    - name: Copy OneShell App artifacts to Content
      shell: bash
      run: |
        mkdir -p ./src/VirtoCommerce.OneShell.Web/Content/one-shell-app
        cp -R ./src/VirtoCommerce.OneShell.Web/one-shell-app/dist/. ./src/VirtoCommerce.OneShell.Web/Content/one-shell-app/
